### ISSUE TITLE
ZARUSD - Forex

### ISSUE THREAD

**Issue by RichardAtCT** [mohamadkhalaj/tradingView-API#1]
Hi @mohamadkhalaj - I am trying to get the data for the usdzar forex paid. When I load it in I just get the following and nothing more:
```
IDC:ZARUSD

'lp'
```

Any ideas? :)

**Comment by mohamadkhalaj** [comment]
Fixed!

**Comment by RichardAtCT** [comment]
A related question - is it possible to get more than lp (last price?) - I am hoping for bid/ask data..

**Comment by mohamadkhalaj** [comment]
I'm not sure about it, The Trading view ws (web socket) API should be analyzed to ensuring about it.

**Comment by abhishekgujarathi** [comment]
Bro what about historical data
